# syntax=docker/dockerfile:1.3
FROM golang:latest AS build
RUN go install github.com/go-delve/delve/cmd/dlv@latest
#dependencies
WORKDIR /aocbot
COPY go.mod .
COPY go.sum .
RUN go mod download

#build
COPY . .
RUN GOOS=linux go build -gcflags="all=-N -l" -o aocbot -v .

FROM ubuntu:latest
RUN apt update
RUN apt install -y fonts-firacode inkscape ca-certificates
ENV SSL_CERT_DIR=/etc/ssl/certs
COPY --from=build /go/bin/dlv /
COPY --from=build /aocbot/aocbot /app/aocbot
CMD ["/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "/app/aocbot"]